import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            <code className={styles.code}>Welcome to my personal website</code>
          </p>
          <div>
            <div>By{" Hardy"}</div>
          </div>
        </div>

        <div className={styles.center}>
          <div className={styles.card}>
            <h1 className={inter.className}>{"</>"}</h1>
          </div>
        </div>

        <div className={styles.description}>Build with love</div>
      </main>
    </>
  );
}
